### ISSUE TITLE
Does cnats support windows?

### ISSUE THREAD

**Issue by gzliudan** [nats-io/cnats#10]
Can we use cnats client on windows platform? And which complier is supported?

**Comment by kozlovic** [comment]
Yes you can. I have just updated the README.md to list the supported platforms. That being said, we don't have a full list of supported platform. Since you seem interested on Windows, I have built the library on a Win7 Pro image, with Visual 2013 Express (64 and 32) and also with the "NMake Makefiles" generator and that works.

If you have any issue building, I will be happy to try to help. Thank you for your interest!

**Comment by kozlovic** [comment]
I hope I have answered your question. I am going to close this issue. Please re-open it if you have any specific question. Thanks!
