### ISSUE TITLE
Check for a valid subject name

### ISSUE THREAD

**Issue by Kazmirchuk** [nats-io/cnats#149]
Currently the only check that cnats performs on a subject is that it is not an empty string. However, a subject with a space or double dots (e.g. foo..bar) is not valid, and gnatsd -DV will report it as -ERR Invalid Subject.
If I open the connection in the pedantic or verbose mode, then my disconnectedHandler gets invoked, and natsConnection_GetLastError indeed reports "Invalid Subject". However, tracking down the actual subject name that triggered the error becomes difficult. Also, getting the connection closed on such error is a bit abrupt.
Did I overlook anything?
Would it be possible to make cnats functions check subject names before sending them to gnatsd? I understand that it may be CPU-intensive, so this check could be optional. Or at least can I see somewhere the regex that is used by gnatsd - then I can add this check in my code.
Thanks in advance.
Petro

**Comment by kozlovic** [comment]
It is not an oversight and is "intentional" that the library is not doing the check (except for NULL or empty string). The reason is that it would duplicate the checks: in the client, then in the server. Also, the server is authoritative and deciding what a valid subject is. If changes or restrictions are added, they are in a single place.

There are several places where the subject is checked. For instance, spaces is not checked per-se, just that it breaks the `PUB` protocol, which expects `PUB <subject> <queue> <sid>`. So if your subject is `foo bar` it would be interpreted as a queue subscriber on queue `bar` for subject `foo` and would not get an error per se. Any other space and you would get a parser error.

Assuming that there is no space, and if pedantic is enabled, then server would check validity of tokens and no wildcards [here](https://github.com/nats-io/gnatsd/blob/5598d5c71162657cc16f244110a9a7d7874a54df/server/sublist.go#L640)

But it does also check that clients do not publish on `_SYS` [here](https://github.com/nats-io/gnatsd/blob/2b58a12123d198d42c4d23c834bea22943312164/server/client.go#L1391)

If you want to add a safe check, I would recommend limiting your subjects to letters and numbers and no spaces and you should be fine. The `*` and `>` are wildcards and not allowed for published messages. The token separator is `.` and a token is at least 1 character long. Again, limit to AZaz09 and you should be fine.

**Comment by cawoodm** [comment]
Really confusing for developers to be told "a subject is just a string", go off and publish to "hello world" and get no response when listening on that channel.

**Comment by kozlovic** [comment]
@cawoodm As described in previous comment, the space between `hello world` is the one that would not really be caught, so no luck here ;-). I would recommend that you familiarize yourself with the subject rules in NATS [here](https://nats-io.github.io/docs/developer/concepts/subjects.html#subject-based-messaging).
