### ISSUE TITLE
About maxPayload

### ISSUE THREAD

**Issue by yhslln** [nats-io/cnats#153]
Hi nats team,
   i am getting started on cnats by using the example named pubstr.c . However i got a mistake while using `natsConnection_PublishString(conn,"foo","hello")` and i find that the natsStatus is NATS_MAX_PAYLOAD. When i debug i find that the maxPayload is zero,but i am pretty sure that the maxPayload on my nats server is not zero.Thus i decide to find where the zero came from, but i failed.So i would like to know why my maxPayload on nats client is zero and the value of maxPayload come from where. Could you please give me some advise? 
By the way, i am using cnats client on AndroidStudio3.0 for a Android App.

**Comment by kozlovic** [comment]
Which version of server and C NATS are you using? Note that there were some LOCALE issues fixed in 1.7.4, so if you are not using the latest (1.7.6, or master), I would recommend you to try with that first. If the problem still persists, you could run the test suite (at least the JSON test):

From your build directory:
```
ctest -R JSON -V
```
and send the output for review.

I am assuming an issue with parsing of the INFO protocol received from server. I don't use a library and do manual parsing. You could add this printf directive [here](https://github.com/nats-io/cnats/blob/master/src/conn.c#L475) like this:
```
    _clearServerInfo(&(nc->info));
    printf("INFO: %.*s\n", len, info);

    s = nats_JSONParse(&json, info, len);
```

**Comment by yhslln** [comment]
Hi ,i find something new.
i try to connect nats server by using C++ socket, and my server log that
`2018/07/31 11:30:48.423506 [ERR] 100.154.131.54:56934 - cid:45 - Error reading from client: Client Parser ERROR, state=0, i=0: proto='"Hlo from C+"...'`
When i use cnats client to connect my server ,nothing happend. But i can capture some TCP request by using wireshark. It seems that TCP request from my AVD can find the host but cant find my server. In addition the natsStatus remains NATS_MAX_PAYLOAD.

**Comment by kozlovic** [comment]
When you connect to a NATS Server, there is a protocol, you can't simply send data otherwise the server will as shown above close the connection with a parser error.
Using the library, the TCP connect is followed by NATS protocol, which is to parse the incoming INFO from the server and then send a CONNECT protocol: https://www.nats.io/documentation/internals/nats-protocol/

Start the server with the `-DV` flag and try to connect your cnats client. See if server is reporting anything. 

Could it be that you have firewall that prevents data from flowing from server to client? 

Not sure why the connection reports NATS_MAX_PAYLOAD.

**Comment by yhslln** [comment]
:),i make a progress.
There may be something wrong when call _jsonGetNum.
I think it begin with this warning when i built it:
`warning: implicit declaration of function 'strtold_l' is invalid in C99 [-Wimplicit-function-declaration]`
`lval = nats_strtold(*ptr, &tail);` 
So the nats_strtold return zero.Thus numbers get from json all become zero, such as port and max_payload.
Should i use C89? or There may be other solutions.
Looking forward to your reply.

**Comment by yhslln** [comment]
In addition , nats_strtold is in<n-unix.h> line 74 :)
`#define nats_strtold(p, t)  strtold_l((p), (t), (natsLib_getLocale()))`

**Comment by kozlovic** [comment]
Sorry for the delay. Can you look for `strtold_l` in android header files if you can find it? If you find the version `strtod_l` instead, then for test modify `nats_strtold` definition in unix.h to `(long double) strtod_l(...` and see if that works for you.

**Comment by kozlovic** [comment]
@yhslln Any update on this? Was it resolved?
