### ISSUE TITLE
Cannot access steaming NATS connection's NATS connection.

### ISSUE THREAD

**Issue by edam** [nats-io/cnats#165]
Unless I'm mistaken, there is no way to get access to a streaming NATS connection's underlying NATS connection!  I think the library should either:

1) Provide a `stanConnection_GetNATSConnection()` that returns the `nc` field, or

2) Provide an alternative stanConnection_Create() that allows you to provide your own NATS conneciton (and expects the caller to close it themselves).

Or am I missing something?

**Comment by kozlovic** [comment]
@edam I departed intentionally from what we did in the Go client. The Streaming connection needs a NATS Connection, but I think it is a bad idea to have it accessible from the outside because then the Streaming connection does not have the control.
What I did instead is to be able to pass a `natsOptions` so that you can configure the Streaming's NATS connection this way. Still, the library will override certain settings and at least I know that it can't be closed by the user while the streaming connection is still alive.

Please check [this](http://nats-io.github.io/cnats/group__stan_conn_opts_group.html#gae3fc9a4daa7f85367811a313857337b4) and also how I do it in one of the examples: https://github.com/nats-io/cnats/blob/master/examples/stan/pub.c#L63.

**Comment by edam** [comment]
What if your application needs to be able to use NATS and NATS streaming?

This is a legitimate use-case... For example, as I understand it, it is not appropriate to use STAN to perform RPC-like "requests" (i.e., with an inbox) like you would with NATS.  And services may separately pub/sub via NATS or STAN depending on whether they care about message delivery or not. We have all of these scenarios where I work now!

As it stands, an application would have to have a separate and thoroughly redundant connection to the server to be able to use NATS and STAN. Multiply this by however many  instances you run, and you start getting a lot of unnecessary connections!

Would you consider at least allowing access to the existing NATS connection in `stanConnection`?

**Comment by kozlovic** [comment]
I may but then I would probably make it such that it would not be possible for the returned connection to be closed. That is, set an internal field that would reject a close if done directly on the returned connection. Makes sense?

**Comment by edam** [comment]
That would be fantastic! 😁

**Comment by edam** [comment]
Want a PR?

**Comment by kozlovic** [comment]
Ok, thanks for the feedback, keep it coming 👍

**Comment by kozlovic** [comment]
I can do it, unless you really want to have a go.

**Comment by edam** [comment]
something like this? #166

**Comment by edam** [comment]
There's still nothing to stop the caller obtaining the NATS connection, closing the STAN connection and then attempting to use the NATS connection.  If you cared about this, you could use a ref count on the NATS connection object.  But the the caller would always have to close it, or it would leak (and not close).

**Comment by kozlovic** [comment]
@edam Did you find any other API design issue that should be addressed before getting out of beta status? If no answer, I may release 1.8.0 this week. Thanks!
