### ISSUE TITLE
Symbol lookup error `protobuf_c_empty_string'

### ISSUE THREAD

**Issue by mgodmere** [nats-io/cnats#173]
I tried compiling against cnats for Linux using the C++ compiler in my own project and get an undefined variable within the library.  

> target_link_libraries(target nats rt)
> /usr/local/lib/libnats.so: undefined reference to `protobuf_c_empty_string'

I used the streaming examples as a guide, but have had no luck building it.  I didn't find a declaration of this variable within cnats so I am guessing this is a variable defined in the cnats protobuf library.  However, when I link against that library it then complains about the declaration at runtime.

> target_link_libraries(target nats pbuf/lib/linux/protobuf-c rt)
> symbol lookup error: /usr/local/lib/libnats.so: undefined symbol: protobuf_c_empty_string

Just wondering how to fix this.

**Comment by kozlovic** [comment]
@mgodmere I see that you have closed this issue. Did you resolve this?

**Comment by bhattashu** [comment]
@mgodmere I am also facing this issue. Did you find a solution?

**Comment by evgry21** [comment]
I am also getting this problem
whats the version of protobuf-c you are supplying along with cnats ?

**Comment by kozlovic** [comment]
@bhattashu @evgry21 Are you planning on using the NATS Streaming API? If not, then compile without support for Streaming (which then won't use the protobuf library). If you do, then you need to include `cnats/pubf/include` directory and link against `cnats/pbuf/lib/linux/libprotobuf-c.so`, but also have that library in your library path when running since this library is not statically linked to the `libnats.so` library.
Note that I am using CMake to build the project and don't have specifics on how to build without on various platforms (that's the point of using CMake as it is cross-platforms). Instructions on how to build with CMake are described [here](https://github.com/nats-io/cnats#building). Note the section explaining how to build the NATS library without streaming:
```
Or, if you don't want to build the NATS Streaming APIs to be included in the NATS library:

cmake .. -DNATS_BUILD_STREAMING=OFF
```

**Comment by altmind** [comment]
Thats a major limitation that we need to DYNAMICALLY link libprotobuf-c.so. There is an open issue on this #191
