### ISSUE TITLE
NATS Streaming Request Support

### ISSUE THREAD

**Issue by wrightleft** [nats-io/cnats#175]
Perhaps I'm miss-understanding NATS streaming, but is there an equivalent streaming function for natsConnection_Request?

**Comment by kozlovic** [comment]
No, request/reply does not make sense with NATS Streaming. In Streaming, a Publish() message is stored in a message log, which means is persistent. Request/Reply is often used to ensure that a message is processed by the consumer, without the need for persistence.

If you have a use case that you want to describe, I may be able to explain better.

**Comment by wrightleft** [comment]
I was just looking for the same synchronous functionality. Am I supposed to instead make a non-streaming NATS connection to the same server and use the request/reply functionality provided there?

**Comment by kozlovic** [comment]
NATS Streaming offers persistence. In a way, it is actually request/reply too. When you publish a message with the streaming API, you can see that as a request/reply between the publisher and the server. The server is the one receiving the request and replies with an OK to say that it received and persisted message. Then, it is a request/reply between the server and the consumer. The consumer sends a reply with an OK saying that it got the message so server should not try to redeliver.

But as you can understand, the publisher and consumer are decoupled. That is, producer doesn't know, nor care, if the consumer actually gets a message.

At the higher level, you could do non streaming request/reply to ensure end-to-end guarantee, that is, the producer sends the request and the consumer sends the reply. This again gives guarantee to the producer that its message has actually been *consumed*, not just persisted.

So if you have a need for both streaming and request/reply, you would use streaming API for persistence and use regular NATS for request/reply. You could have your own NATS connection or get the NATS connection from the NATS Streaming connection.

Hope this helps.

**Comment by kozlovic** [comment]
That's because by default NATS Streaming server embeds a NATS Server to communicate with clients. But really you should see the NATS Streaming server as an entity connecting to a NATS Server to which your clients connect to.

So you can indeed create (or use) a NATS Connection to connection to the streaming server, but in reality, you are connecting to the NATS Server. I would recommend that you understand the difference. [This](https://github.com/nats-io/nats-streaming-server#concepts) in the NATS Streaming server repo may help.
