### ISSUE TITLE
NATS Streaming and natsOptions_SetRetryOnFailedConnect

### ISSUE THREAD

**Issue by wrightleft** [nats-io/cnats#176]
The functionality provided by natsOptions_SetRetryOnFailedConnect doesn't seem to be supported with stanConnection_Connect. NATS_NOT_YET_CONNECTED is correctly returned, but the connection pointer is still null.

**Comment by kozlovic** [comment]
Not sure I will be able to support that. You have to understand that in core NATS, there is not connect response from the server and client can buffer outgoing publish calls while trying to connect because there is no guarantee given to the user that a publish call succeeds or not.

For streaming, the library cannot do anything if not connected to the server. If it were to "buffer" the outgoing publish calls, then the Publish() would return "OK" but that is wrong because there would no guarantee that the server ever receive and persists those. At least this is the case for synchronous sends.

**Comment by kozlovic** [comment]
Still, thanks for the report because I will fix that so the connect calls returns `NATS_NO_SERVER` for now, and will add a note that `natsOptions_SetRetryOnFailedConnect` is ignored - at least for now.

**Comment by kozlovic** [comment]
Closing this for now. See #177 and #179
