### ISSUE TITLE
Threading control using CNATS

### ISSUE THREAD

**Issue by yanivge** [nats-io/cnats#195]
This is a question / feature request  - I could not find CNATS forum for posting this question... 

I have an application that use CNATS as a publisher (publish only). 
In such case I would expect CNATS to open only a single thread (just for posting) but in fact 4 threads are opened. 
1 thread is listener - this i can understand 
1 thread for posting, 
2 more???? 

Specifically - I want to be able to control the threading on my setup and to define the behavior. 
Personally - since I am only doing publishing, and the rate of the publish is not extremely high (batching messages in the application level) - I think 1 thread should be enough. 

summary: 
(1) I would like to know more about the roll of each thread.
(2) I would like to have an option parameter that controls the threading mechanism.

**Comment by kozlovic** [comment]
There is a FAQ section that partly answers your questions: https://github.com/nats-io/cnats#faq
Here is the relevant excerpt:

----
What is the threading model of the library?

The library uses some threads to handle internal timers or dispatch asynchronous errors for instance. Here is a list of threads created as a result of the user creating NATS objects:

Each connection has a thread to read data from the socket. If you use an external event loop, this thread is not created.

Each connection has a thread responsible for flushing its outgoing buffer. If you create the connection with the natsOptions_SetSendAsap() option, this thread is not created since any outgoing data is flushed right away.

Each asynchronous subscription has a thread used to dispatch messages to the user callback. If you use nats_SetMessageDeliveryPoolSize(), a global thread pool (of the size given as a parameter to that function) is used instead of a per-async-subscription thread.

----

So regardless if you only publish, the library needs some threads to handle timers and async callbacks. See if the above helps you.

**Comment by kozlovic** [comment]
Closing for now, please re-open if you have more questions.
