### ISSUE TITLE
libevent intgration and subscription callback

### ISSUE THREAD

**Issue by vikramkarandikar** [nats-io/cnats#203]
I am trying to understand how libevent integration and subscription callbacks work together.

as I understand the current approach in cnats library is allow using single libevent loop by sharing event base created in the application.
but the (libevent adapter) feeds the read messages back to nats library and then cnats library invokes appropriate subscription callback function (probably in some separate thread then we fed the message?)

if this is the case then does this mean that onMsg (typical name for subscription callback) and libevent main thread still need to handle concurrency?
Every new connect would have a separate subscription callback calling thread?

Is there way from application perspective to make everything single threaded and let cnats send/ receive messages using it's own threads?

**Comment by kozlovic** [comment]
If you decide to use libevent, what this does is suppress the need for the c nats own thread to read data from the socket. Some callbacks are registered so that when there is read/write events, libevent will invoke those callbacks, which in turn will parse the byte array and then invoke appropriate calls in the NATS library. For instance, parsing a message results in that message being given to appropriate subscriptions (if any).
You are correct that in the case of an async subscription, the NATS library will still have its own thread to dispatch the message. Therefore, the onMsg callback as you describe will be invoked from a different thread than the libevent event loop.

**Comment by vikramkarandikar** [comment]
Okay, so application has to be thread aware to use cnats. 
I am trying to get cnats work in a single thread setup. Let’s see how I can achieve it. 

Thanks for your reply.

**Comment by kozlovic** [comment]
You can explore the use of synchronous subscriptions (`natsConnection_SubscribeSync(&sub, nc, "foo");` and `natsSubscription_NextMsg(&msg, sub, <timeout>);`) if somehow you are breaking out of the even loop, etc and can call NextMsg with very small timeout because message will have been put in the subscription's internal queue during processing of read events and so will be available, or if there was no message for this subscription, NextMsg() will return timeout. But I don't think this would perform very well..

**Comment by kozlovic** [comment]
Closing for now. Will re-open if you have further questions.
