### ISSUE TITLE
Building in raspbian 

### ISSUE THREAD

**Issue by SpaceKennel** [nats-io/cnats#207]
![image](https://user-images.githubusercontent.com/26978199/54256847-ca0fc780-4576-11e9-8dc9-b1619924ec30.png)
Is there any way to solve this problem?

**Comment by kozlovic** [comment]
@SpaceKennel I bet that it would have previously worked, but PR #183 may have broken that.

I was able to build correctly on an arm32v6/alpine docker image recently, so that was ok, but I just downloaded the `resin/rpi-raspbian` and indeed got the error you got. So instead of trying to exclude this one specifically, I have introduced a new build flag that will allow bypassing the spin attempts.

I have updated the README in the PR #208, but basically you will have to enable the `NATS_BUILD_NO_SPIN` CMake option.
```
cmake .. -DNATS_BUILD_NO_SPIN=ON
```
and call `make` again.
