### ISSUE TITLE
asio adapter

### ISSUE THREAD

**Issue by feverzsj** [nats-io/cnats#43]
is it possible to use cnats with boost.asio?

**Comment by kozlovic** [comment]
Sorry about the delay I have been sick since Friday.

The answer is I don't know. The library is in C++ and not my forte. You would have to look if you could write an adapter as the ones for `libuv` and `libevent`. 

The key is that the C NATS library creates the socket and initiates the connection (and reconnection) to the server. The adapter needs to pass some callbacks that implements the initialization of the adapter, the binding of a NATS connection and socket to the event loop, the read and write callbacks and a detach for when a connection is closed.

The NATS library will then invoke those when it needs to read/write. 

Check one of the subscriber example using libevent: https://github.com/nats-io/cnats/blob/master/examples/libevent-sub.c

**Comment by kozlovic** [comment]
Closing this issue for now.

**Comment by wrightleft** [comment]
I just want to add a request for this feature. For a process that already has an asio io service, it would be silly to add yet another thread pool.

**Comment by ecoindev** [comment]
@kozlovic Any progress on this issue?

@feverzsj 
Did you manage to implement the integration of this library with boost:asio?

I'm trying to figure out what's easier: implement the NATS protocol from scratch, using asio abstractions or still screw the adapter, as @kozlovic suggests.

**Comment by kozlovic** [comment]
@ecoindev No progress and no plan to look into it, sorry.

**Comment by h4tr3d** [comment]
Just to share... My simple Asio (Standalone) Adapter for nats.c: https://gist.github.com/h4tr3d/d65b561bdf971647e546757dd4909c11

Possible use:

```c++
// asio::io_context io;
// ...
//  natsOptions_SetEventLoop(opts, &io,
//                           NatsAsioAdapter::asioAttach,
//                           NatsAsioAdapter::asioRead,
//                           NatsAsioAdapter::asioWrite,
//                           NatsAsioAdapter::asioDetach);
// ...
// io.run();
```
