### ISSUE TITLE
static string in nats.h

### ISSUE THREAD

**Issue by ohler55** [nats-io/cnats#5]
nats.h defines a static const char* (NATS_DEFAULT_URL). This has the effect of causing compiler warnings unless the variable is used. Either a #define or an extern declaration with the value set in some .c file would be a reasonable fix for this.

I'd put in a PR but wasn't sure what your preferences were.

**Comment by kozlovic** [comment]
Sorry for the delay. Did not see that because I use -Wno-unused-variable. But you have a good point, and there are plenty of others that are defined in natsp.h that would cause the same problem. I think that the #define approach will be easier, but you are welcome to submit a PR the way you would fix it. I am going to looking into it myself and will decide which one is better ;-)

PS: I am not a CMake expert and having a problem to have examples depend on 'install' so that they find the .h files from the install directory. As of now, they build using the src/ directory, which is not what it should be. If you know how to fix that, that would be a great help!.

**Comment by ohler55** [comment]
I haven't used cmake so we are both in the same spot on that. I generally just use regular make and then just get by with the basics.

I'll look at submitting a PR. I want to check where and how the default is used. I suspect you are right and a #define is the simplest approach.

**Comment by ohler55** [comment]
:+1:

**Comment by kozlovic** [comment]
I committed a change that fixes this with the use of `#define`. Also remove unused variables.
