### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by rFronteddu** [nats-io/cnats#54]
Hello, I noticed that if I don't call natsConnection_ConnectTo after including #include"nats.h" cnats crashes on windows.

Debugger report:

Unhandled exception at 0x779B9F83 (ntdll.dll) in launcher.exe: 0xC0000005: Access violation writing location 0x00000004.
If there is a handler for this exception, the program may be safely continued.

natsMutex_Lock(natsMutex *m)
{
    // If gLockSpinCount > 0, the mutex has been created as as spin lock,
    // so we don't have to do anything special here.
    EnterCriticalSection(m); //< ------  crash here with access violation
}

Where m is NULL. 

I will try to reproduce the issue later in the week to be sure that it is not actually me being a bad programmer. Just wanted to know if you noticed anything like that.

**Comment by kozlovic** [comment]
This is because the library registers a cleanup function to execute on exit. If you have not called `nats_Open()` either directly or through functions that do it implicitly (such as `natsConnection_Connect[To]()`, then this will happen. I added a fix for non Windows build to actually do nothing if I detect that the library was not opened once, and will add that to the Windows version. Thanks for the report!

**Comment by rFronteddu** [comment]
Sweet! Thanks!
