### ISSUE TITLE
Question about Publishing

### ISSUE THREAD

**Issue by qrpike** [nats-io/cnats#59]
Are publish's in a separate thread or will they block the thread the connection is created in?

Thanks! - Great work no the library btw

**Comment by kozlovic** [comment]
Thanks for the compliment!

For throughput reasons (and to mimic the Go client this library is based on), the client library uses a buffer for all socket writes. It is either flushed in the thread where the publish occurs (or the create of a subscription - since this is sending a protocol message to the server) if the buffer is full and needs flushing, or in a separate thread (the flusher thread).
To reduce latency, the user's Request calls do flush the buffer in place and do not rely on the flusher thread.

**Comment by qrpike** [comment]
@kozlovic Thanks again!
