### ISSUE TITLE
Publish Performance

### ISSUE THREAD

**Issue by ugiwgh** [nats-io/cnats#83]
I have test the following code.
`    for(i=1;i<101;i++)
    {
      for(j=1;j<1001;j++)
      {
        natsConnection_Publish(nc,subject,bf,bfsz); // bfsz=136
      }
    }`
I use two nodes. One node A publish 10w messages, cost about 330ms, and take 8.9 cpu. The other node B publish 10w messages, cost about 1363ms, and take 3.3 cpu.

I want to improve node B performance, and it can publish 10w messages within 1000ms. I don't known the performance bottleneck.

**Comment by kozlovic** [comment]
As you wrote, the same application, the same library (assuming they are at the same version) produces different performance results.
So the difference has to be based on the environment. It could be CPU speed, network card (check bandwidth). Are you connecting to a local NATS Server on each node or connecting to a different host? (if so, that adds to the variables).

**Comment by kozlovic** [comment]
Also remember a case where user had issues due to anti-virus that was impacting the results.. so something else to check.

**Comment by ugiwgh** [comment]
The node A is CentOS Linux release 7.3.1611, Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz, 2 socket 6 core 12 thread.
The node B is Red Hat Enterprise Linux Server release 7.0, Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz, 1 core, vmware virtual machine.
The NATS Server install on node A.
Yes, it's  the same application, and the same library. And compiled on node A.
The node A and node B publish the message at the same time.
The node A txkB/s is about 15654.94, and rxkB/s is about 15654.94 on lo.
The node A txkB/s is about 190.15, and rxkB/s is about 13467.67 on enp129s0f1.
The node B txkB/s is about 17715.47, and rxkB/s is about 645.96 on eno16777736.

**Comment by kozlovic** [comment]
First, you should try a test where each node has its own NATS Server running locally and see how fast each node can go.
Then, from what I understand, the NATS Server is currently running on node A, so obviously application running on node A will be faster since it uses loopback I presume. Try reversing the situation of having NATS Server running on node B and see if now node B's application becomes the fastest or if performance is still subpar.

Note that node B is a VM with single core, as you describe, so I expect this to not perform too well with both NATS Server and client being multi-threaded (internally).

Regardless, performance seem low compare to what I can get on a Ubuntu VM (running from a Macbook Pro). I have modified `examples/nats-publisher` to send a byte array of 136 bytes:
```
root@5455f94d3023:/home/ivan/cnats/build_linux# examples/nats-publisher -count 10000000
Sending 10000000 messages to subject 'foo'
Out Msgs:         1 - Out Bytes:       136 - Reconnected:   0
Out Msgs:   6240338 - Out Bytes: 848685968 - Reconnected:   0
Out Msgs:  10000000 - Out Bytes: 1360000000 - Reconnected:   0

Sent 10000000 messages in 1628 milliseconds (6142506 msgs/sec)
```
This is without any subscriber on `foo` running, and get more than 6 million messages per second.

**Comment by ugiwgh** [comment]
I have test on node B. To install NATS Server on node B, and node B publish the message to itself. It take 3.6 cpu, rxkB/s 15827.40, txkB/s 15827.40 on lo, cost 215ms.

**Comment by kozlovic** [comment]
So same than node A when server running locally there. Now try server running on node B and application on node A connecting to server on node B. If application on node A now performs as application on node B in original test, then this is the cost of network. If node A connecting to server on node B is still doing much better, then this is the cost of network for the VM.

**Comment by kozlovic** [comment]
It has been 3 weeks without an update. I am closing the issue now, don't hesitate to re-open if you have new information to provide. Thanks!
