### ISSUE TITLE
Installed header files include "nats.h", not "nats/nats.h"

### ISSUE THREAD

**Issue by mdevan** [nats-io/cnats#90]
Two of the installed header files include "nats.h", rather than "nats/nats.h":

```
$ pwd
/usr/local/include/nats
$ grep -ir "nats\.h" .
./adapters/libevent.h:#include "nats.h"
./adapters/libuv.h:#include "nats.h"
```

This causes warnings (from the pragma in "nats.h"):

```
$ clang  libuv-sub.c  -luv -lnats
In file included from libuv-sub.c:5:
In file included from ./examples.h:7:
/usr/local/include/nats.h:7:2: warning: "`#include <nats.h>` is deprecated. Please use `#include <nats/nats.h>`"
      [-W#warnings]
#warning "`#include <nats.h>` is deprecated. Please use `#include <nats/nats.h>`"
 ^
1 warning generated.
```

**Comment by kozlovic** [comment]
Thanks for the report!

With the way you run `clang`, being in the examples directory, you should not be able to compile anyway. It should complain that `libuv-sub.c` is trying to include `adapters/libuv.h` which would not be found. Editing this file would move to the next problem of `examples.h` issue trying to include `nats.h`.

The issue is that you do not specify the include directive, so the default `/usr/local/include` is used. If you were to specify the `-I` directive to select the include path, it would work without any modification to the examples files and installed headers:
```
clang -I/usr/local/include/nats libuv-sub.c ...
```
That being said, I am going to modify the headers to include `../nats.h` instead, so that it will work both when building examples with cmake (which includes the repo's `src` directory where `nats.h` and `adapters` directory are located) and for users that don't explicitly set the include directive (defaults to `/usr/local/include`), granted that their files include `nats/nats.h` and `nats/adapters/libuv.h` (if using libuv).

**Comment by mdevan** [comment]
Thanks for the fix, can confirm that the installed headers now refer proper paths ("fix_installed_adapters_headers" branch).
